CREATE TABLE IF NOT EXISTS school.students
(STUDENT_ID SERIAL PRIMARY KEY,
GROUP_ID INT,
FIRST_NAME TEXT,
LAST_NAME TEXT,
CONSTRAINT GROUP_ID_FK
 FOREIGN KEY (GROUP_ID)
 REFERENCES school.groups (ID));