DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS public.group CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS student_course CASCADE;
CREATE TABLE IF NOT EXISTS course (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT
);
CREATE TABLE IF NOT EXISTS public.group (
    ID SERIAL PRIMARY KEY,
    NAME TEXT
);
CREATE TABLE IF NOT EXISTS student (
    ID SERIAL PRIMARY KEY,
    GROUP_ID INT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    CONSTRAINT GROUP_ID_FK
    FOREIGN KEY (GROUP_ID)
    REFERENCES public.group (ID)
);
CREATE TABLE IF NOT EXISTS student_course (
    STUDENT_ID INT,
    COURSE_ID INT,
    CONSTRAINT STUDENT_ID_FK
    FOREIGN KEY (STUDENT_ID)
    REFERENCES student (ID)
    ON DELETE CASCADE,
    CONSTRAINT COURSE_ID_FK
    FOREIGN KEY (COURSE_ID)
    REFERENCES course (ID)
    ON DELETE CASCADE
);