DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS courses_students CASCADE;
CREATE TABLE IF NOT EXISTS courses (
    ID SERIAL PRIMARY KEY,
    NAME TEXT,
    DESCRIPTION TEXT
);
CREATE TABLE IF NOT EXISTS groups (
    ID SERIAL PRIMARY KEY,
    NAME TEXT
);
CREATE TABLE IF NOT EXISTS students (
    STUDENT_ID SERIAL PRIMARY KEY,
    GROUP_ID INT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    CONSTRAINT GROUP_ID_FK
    FOREIGN KEY (GROUP_ID)
    REFERENCES groups (ID)
);
CREATE TABLE IF NOT EXISTS students_courses (
    STUDENT_ID INT,
    COURSE_ID INT,
    CONSTRAINT STUDENT_ID_FK
    FOREIGN KEY (STUDENT_ID)
    REFERENCES students (STUDENT_ID)
    ON DELETE CASCADE,
    CONSTRAINT COURSE_ID_FK
    FOREIGN KEY (COURSE_ID)
    REFERENCES courses (ID)
    ON DELETE CASCADE
);