CREATE SCHEMA SCHOOL;
CREATE TABLE SCHOOL.course (
    ID IDENTITY UNIQUE,
    NAME TEXT,
    DESCRIPTION TEXT
);
CREATE TABLE IF NOT EXISTS SCHOOL.group (
    ID INT AUTO_INCREMENT UNIQUE NOT NULL,
    NAME TEXT
);
CREATE TABLE IF NOT EXISTS SCHOOL.student (
    ID IDENTITY UNIQUE,
    GROUP_ID INT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    CONSTRAINT GROUP_ID_FK
    FOREIGN KEY (GROUP_ID)
    REFERENCES SCHOOL.group (ID)
    ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS SCHOOL.student_course (
    STUDENT_ID INT,
    COURSE_ID INT,
    CONSTRAINT STUDENT_ID_FK
    FOREIGN KEY (STUDENT_ID)
    REFERENCES student (ID)
    ON DELETE CASCADE,
    CONSTRAINT COURSE_ID_FK
    FOREIGN KEY (COURSE_ID)
    REFERENCES course (ID)
    ON DELETE CASCADE
);